### ISSUE TITLE
stretch thicccc

### ISSUE THREAD

**Issue by itspacchu** [TheAwesomeShaz/stretchy-stealer#1]
( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)

**Comment by TheAwesomeShaz** [comment]
nah bro just bugs nothing is gud nothing is thicc

**Comment by itspacchu** [comment]
( ͡° ͜ʖ ͡°)
